default: &default
  adapter: postgresql
  encoding: unicode
  username: service
  password: service
  host: localhost
  pool: 5
  database: twilight

development:
  adapter: postgresql
  encoding: unicode
  username: service
  password: service
  host: localhost
  pool: 5
  database: twilight_dev


# production:
#   adapter: postgresql
#   encoding: unicode
#   username: service
#   password: service
#   host: localhost
#   pool: 5
#   database: twilight
